---

- name: "Restart ssh service"
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: "Restart ntp service"
  become: true
  ansible.builtin.service:
    name: ntp
    state: restarted

- name: "Restart rng-tools service"
  become: true
  ansible.builtin.service:
    name: rng-tools
    state: restarted

- name: "Reload ufw service"
  community.general.ufw:
    state: reloaded

- name: "Restart psad service"
  ansible.builtin.shell: |
    psad -R
    psad --sig-update
    psad -H
  tags:
    - skip_ansible_lint

- name: "Reload systemd"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Restart prometheus service"
  become: true
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: true
