---

- name: "Auditing | Lynis - Install lynis packages"
  become: true
  ansible.builtin.package:
    name: "{{ package }}"
    state: present
  loop:
    - lynis
    - host
  loop_control:
    loop_var: package

- name: "Auditing | Lynis - Update lynis"
  ansible.builtin.shell: |-
    /usr/sbin/lynis update info
  tags:
    - skip_ansible_lint
